# Generated by Django 3.1.7 on 2021-04-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypizzaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypizzastore',
            name='pizza_sizes',
        ),
        migrations.AddField(
            model_name='mypizzastore',
            name='pizza_sizes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mypizzaapp.pizzasize'),
            preserve_default=False,
        ),
    ]
